### ISSUE TITLE
deprecated subdependencies found

### ISSUE THREAD

**Issue by GZTimeWalker** [alienfast/vite-plugin-i18next-loader#23]
WARN  2 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6
 
```
devDependencies:
vite-plugin-i18next-loader 2.0.14
└─┬ glob-all 3.3.1
  └─┬ glob 7.2.3
    └── inflight 1.0.6
```

**Comment by GZTimeWalker** [comment]
Suggestion: use `>=3.3.1` instead of `^3.3.1` if you want to allow user to upgrade the peer dependencies

But it seems to be the issue for `glob-all`?

Ref to https://github.com/jpillora/node-glob-all/issues/30

Maybe you can get rid of this package?

**Comment by rosskevin** [comment]
I'm working on the swap to node-glob, thank you for the linked issue.

**Comment by GZTimeWalker** [comment]
Thanks! Waitng for good news!

**Comment by rosskevin** [comment]
[3.0.0 released](https://github.com/alienfast/vite-plugin-i18next-loader/releases/tag/v3.0.0)
